# action.yaml
name: 'Notebook Publish Github Action'
description: 'A Github Action that takes an input and returns the square of the number'
inputs:
  nbsource:
    description: 'Notebook source folder name'
    required: true
    default: 'src'
  nbtarget:
    description: 'Notebook target folder name (contains executed notebooks)'
    required: true
    default: 'target/note'
  nbdoc:
    description: 'Notebook target folder name for HTML (contains converted webpages)'
    required: true
    default: 'target/doc'
  nbcommon:
    description: 'Notebook common dependencies that are expected to be present instead of installed within the notebook'
    required: false
    default: ''
outputs:
  committed:
    description: 'Whether the nbaction was committed'
    value: ${{ steps.nbaction.outputs.committed }}
  commitSHA:
    description: 'short SHA of the committed change'
    value: ${{ steps.nbaction.outputs.commit_sha }}

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        # caching pip dependencies
        cache: 'pip'
    - name: Update Dependencies and env variables
      run: |
        python -m pip install --upgrade pip -r requirements.txt
        echo "NB_SOURCE_PATH=${{ inputs.nbsource }}" >> $GITHUB_ENV
        echo "NB_TARGET_PATH=${{ inputs.nbtarget }}" >> $GITHUB_ENV
        echo "NB_DOC_PATH=${{ inputs.nbdoc }}" >> $GITHUB_ENV
      shell: bash
    - name: Run nbaction
      id: nbaction
      run: python src/nbaction.py
      shell: bash

