# action.yaml
name: 'Notebook Publish Github Action'
description: 'A Github Action that takes a sequence of notebooks and executes, then publishes them in specified folders'
inputs:
  nbsource:
    description: 'Notebook source files'
    required: true
  nbtarget:
    description: 'Notebook target folder name (contains executed notebooks)'
    required: true
    default: 'target/note'
  nbdoc:
    description: 'Notebook target folder name for HTML (contains converted html docs)'
    required: true
    default: 'target/doc'
  nbcommon:
    description: 'Notebook common dependencies that are expected to be present instead of installed within the notebook'
    required: false
    default: ''
outputs:
  processed:
    description: 'list of processed output files'
    value: ${{ steps.nbaction.outputs.processed }}

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        # caching pip dependencies
        cache: 'pip'
    - name: Update Dependencies and env variables
      run: |
        python -m pip install --upgrade pip -r requirements.txt
        echo "NB_SOURCES=${{ inputs.nbsource }}" >> $GITHUB_ENV
        echo "NB_TARGET_PATH=${{ inputs.nbtarget }}" >> $GITHUB_ENV
        echo "NB_DOC_PATH=${{ inputs.nbdoc }}" >> $GITHUB_ENV
      shell: bash
    - name: Run nbaction
      id: nbaction
      run: python src/nbaction.py
      shell: bash
    - name: Commit generated files
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Actions"
        for file in ${{ steps.nbaction.outputs.processed }}; do
          echo "Adding $file to PR"
          git add file
        done
      shell: bash

