# action.yaml
name: 'Notebook Publish Github Action'
description: 'A Github Action that takes an input and returns the square of the number'
inputs:
  nbinput:
    description: 'Notebook source folder name'
    required: true
    default: 'src'
  nboutput:
    description: 'Notebook target folder name (contains executed notebooks)'
    required: true
    default: 'target/note'
  nbhtml:
    description: 'Notebook target folder name for HTML (contains converted webpages)'
    required: true
    default: 'target/html'
  num:
    description: 'Enter a number'
    required: true
    default: "1"
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        # caching pip dependencies
        cache: 'pip'
    - name: Install Dependencies
      run: python -m pip install --upgrade pip -r requirements.txt
      shell: bash
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update notebooks
      run: |
          python -m pip install nbconvert nbformat
          mkdir -p ${{ inputs.nboutput }}
          mkdir -p ${{ inputs.nbhtml }}
          for n in ${{ inputs.nbinput }}/*.ipynb; do jupyter nbconvert --to notebook --execute "$n" --output-dir=${{ inputs.nboutput }}/; done
          for n in ${{ inputs.nboutput }}/*.ipynb; do jupyter nbconvert --to html "$n" --output-dir=${{ inputs.nbhtml }}/; done
      shell: bash
    - name: commit updated files
      uses: EndBug/add-and-commit@v9
      id: commit
      with:
        author_name: Astro Bot
        commit: --signoff

