# action.yaml
name: 'Notebook Publish Github Action'
description: 'A Github Action that takes an input and returns the square of the number'
inputs:
  nbinput:
    description: 'Notebook source folder name'
    required: true
    default: 'src'
  nboutput:
    description: 'Notebook target folder name (contains executed notebooks)'
    required: true
    default: 'target/note'
  nbhtml:
    description: 'Notebook target folder name for HTML (contains converted webpages)'
    required: true
    default: 'target/html'
  nbcommon:
    description: 'Notebook common dependencies that are expected to be present instead of installed within the notebook'
    required: false
    default: ''
outputs:
  committed:
    description: 'Whethher the nbaction was committed'
    value: ${{ steps.nbaction.outputs.committed }}
  commitSHA:
    description: 'short SHA of the committed change'
    value: ${{ steps.nbaction.outputs.commit_sha }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        # caching pip dependencies
        cache: 'pip'
    - name: Install Dependencies
      run: python -m pip install --upgrade pip -r requirements.txt
      shell: bash
    - name: Update notebooks
      run: |
          pwd
          python -m pip install nbconvert nbformat
          [ -z "${{ inputs.nboutput }}" ] && echo "No common dependencies" || python -m pip install ${{ inputs.nbcommon }}
          mkdir -p ${{ inputs.nboutput }}
          mkdir -p ${{ inputs.nbhtml }}
          GIT_PR_FILES=
          for n in ${{ inputs.nbinput }}/*.ipynb; do \
            GIT_PR_FILES="$n $GIT_PR_FILES"
            jupyter nbconvert --to notebook --execute "$n" --output-dir=${{ inputs.nboutput }}/; \
          done
          for n in ${{ inputs.nboutput }}/*.ipynb; do \
            GIT_PR_FILES="$n $GIT_PR_FILES"
            jupyter nbconvert --to html "$n" --output-dir=${{ inputs.nbhtml }}/; \
          done
          echo "GIT_PR_FILES=$GIT_PR_FILES" >> $GITHUB_ENV
          echo "Workspace: $GITHUB_WORKSPACE Processed: $GIT_PR_FILES"
      shell: bash
    - name: commit updated files
      uses: EndBug/add-and-commit@v9
      id: nbaction
      with:
        default_author: github_actions
        message: Show github actions logo
        committer_name: Github Actions
        commit: --signoff
        add: $GIT_PR_FILES
        cwd: $GITHUB_WORKSPACE

