# .github/workflows/test_action.yaml
name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    name: Return's the number square
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Fetch num squared
        id: get_square
        uses: ./ 
        with:
          num: 11
      - name: Print the square
        run: echo "${{ steps.get_square.outputs.num_squared }}" >> $GITHUB_OUTPUT