# .github/workflows/test_action.yaml
name: Test Action
on: [push]

jobs:
  build-notebooks:
    runs-on: ubuntu-latest
    name: Test the notebook publish
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run nbaction
        id: commit
        uses: ./ 
        with:
          nbsource: 'src'
          nbtarget: 'target/note'
          nbdoc: 'target/html'
          nbcommon: 'numpy pandas matplotlib '
      - name: commit
        uses: peter-evans/create-pull-request@v4